config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'home/index'
  get 'home', to: 'home#index'
  
  #get 'contents', to: 'contents#index'
  #get 'contents/new', to: 'contents#new'
  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  validates :title, :description, presence: true

  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  validates :name, presence: true, uniqueness: {scope: :user_id} 
  
  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [ :show, :edit, :update, :destroy]
  
  def index
    @contents = current_user.contents

    tag_names = params[:tags]

    if tag_names.present?
      @contents = @contents.joins(:tags).where(tags: {name: tag_names}).distinct
    end
  end

  def new
    @content = Content.new
  end

  def show
    #@content = Content.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end

  def create
    @content = current_user.contents.build(content_params)
    
    if @content.save 
      associate_tags!
      redirect_to contents_path, notice: 'Content successfully created'
    else     
      render :new
    end
  end

  def edit
    #@content = Content.find(params[:id])
  end

  def update
    #@content = Content.find(params[:id])
    if @content.update(content_params)
      associate_tags!
      redirect_to contents_path, notice: 'Content successfully updated'
    else     
      render :edit
    end
  end

  def destroy
    #@content = Content.find(params[:id])
    @content.destroy

    redirect_to contents_path, notice: "Content successfully deleted id: #{@content.id}"
  end

  private

  def set_content
    @content = Content.find(params[:id])
  end

  def tags_params
    params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
  end

  def content_params
    params.require(:content).permit( :title, :description)
  end

  def associate_tags!
    tags = tags_params.map do |tag_name|
      current_user.tags.where(name: tag_name).first_or_initialize
    end

    @content.tags = tags
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags_data = current_user.contents.joins(:tags).group('tags.name').count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contents/_form.html.erb
<% if content.errors.any? %>
    <div class='errors'>
        Errors:  <%= content.errors.full_messages.join(", ") %>
        <BR><BR>
    </div>    
<% end %>

<%= form_with(model: content, local: true) do |form|%>
    <br><br>
    <div class='form-group'>

        <div class="input-group">            
            <%= form.label :title, class: "input-group-text", id: "inputGroup-sizing-sm" %>
            <%= form.text_field :title, class: 'form-control' %>
        </div>
        <BR>
        <div class="input-group">
            <%= form.label :description, class: 'input-group-text', id: 'addon-wrapping' %>                      
            <%= form.text_area :description, class: 'form-control'%> 
        </div>
        <BR><BR>
        <div class='field'>  
            <%= form.label :tags, class: "input-group-text", id: 'addon-wrapping' %>      
            
            <%= form.select :tags, 
            options_for_select(current_user.tags.pluck(:name),
                                content.tags.pluck(:name)), {},
            { class: 'form-control select2', multiple: 'multiple'} 
            %>        
        </div>
        <BR>
        <div>
            <%= form.submit 'Save', class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/contents/edit.html.erb
<h1>Edit Content</h1>

<%= render 'form', content: @content %>

app/views/contents/index.html.erb
<%= link_to 'New content', new_content_path %>

<h2>Contents</h2>

<%= form_tag(contents_path, method: :get) do %>
    <div class='form-group' >
        <%= label_tag :tags %>
        <%= select_tag 'tags[]', 
           options_for_select(current_user.tags.pluck(:name), params[:tags]),
           class: 'select2 form-control', multiple: 'multiple' 
        %>        
    </div>
    <div class='actions' >
        <%= submit_tag 'Search', class: 'btn btn-primary'%>
    </div>
<% end %>

<BR><BR>

<% @contents.each do |content| %>
    <%= link_to 'Show', content_path(content) %>
    <%= link_to 'Edit', edit_content_path(content) %>
    <%= link_to 'Delete', content_path(content), method: :delete , data: { confirm: 'Are you sure?' }%>
    <strong>Title:</strong> <%= content.title %>
    <strong>Description:</strong> <%= content.description %>
    <strong>Tags:</strong> <%= content.tags.pluck( :name ).join(", ") %>
   
    <BR>
<% end %>

app/views/contents/new.html.erb
<h1>New Content</h1>

<%= form_with(model: @content, local: true) do |form|%>
    <div class='field'>
        <%= form.label :title%>
        <%= form.text_field :title %>
    </div>
    <div class='field'>
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/contents/show.html.erb
<h1><%= @content.title %></h1>

<p>
    
    <%= raw @markdown.render(@content.description) %>
    <br>
    <br>
    <Strong>Tags: </strong><%= @content.tags.pluck(:name).join(', ') %>
</p>

app/views/home/index.html.erb
<h1>CLOUD TAGS - <%= current_user.email %></h1>

<% @tags_data.each do |tag_name, count| %>
    <% font_size = count * 20%>
    <span style='font-size: <%= font_size > 70 ? 70 : font_size %>px'>
        <%= link_to tag_name, contents_path(tags: [tag_name]), style:'text-decoration: none' %>        
    </span>    
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MindApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <div class='topo'>
        <% if user_signed_in? %>
          <%= link_to 'Home', home_path, class:'btn btn-primary'%>
          <%= link_to 'Contents', contents_path, class:'btn btn-primary' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete , class:'btn btn-primary'%>
        <% end %>
      </div>    

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>